baseURL = "https://tech.feminizidmap.org"
languageCode = "en-us"
title = "Tech.Feminizidmap.org"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 20

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2
    
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
    
[params]
  homepage_button_link = '/docs'
  homepage_button_text = 'Read the docs'
  #homepage_image = '/images/terminal.gif'
  ## You can enable to add anchor links to header elements
  enable_anchor_link = true
  mainSections = ['blog', 'docs']

[params.logo]
  mobile = "/assets/tech-logo.png"
  standard  = "/assets/tech-logo.png"
